import c from "../../rails/config/countries.json";

export const CURRENCIES = [
  { name: "USD (United States Dollar)", value: "USD" },
  { name: "AED (United Arab Emirates Dirham)", value: "AED" },
  { name: "ARS (Argentine Peso)", value: "ARS" },
  { name: "AUD (Australian Dollar)", value: "AUD" },
  { name: "BGN (Bulgarian Lev)", value: "BGN" },
  { name: "BWP (Botswana Pula)", value: "BWP" },
  { name: "CAD (Canadian Dollar)", value: "CAD" },
  { name: "CHF (Swiss Franc)", value: "CHF" },
  { name: "CLP (Chilean Peso)", value: "CLP" },
  { name: "CRC (Costa Rican Colón)", value: "CRC" },
  { name: "CZK (Czech Koruna)", value: "CZK" },
  { name: "DKK (Danish Krone)", value: "DKK" },
  { name: "EGP (Egyptian Pound)", value: "EGP" },
  { name: "EUR (Euro)", value: "EUR" },
  { name: "GBP (British Pound)", value: "GBP" },
  { name: "GEL (Georgian Lari)", value: "GEL" },
  { name: "GHS (Ghanaian Cedi)", value: "GHS" },
  { name: "HKD (Hong Kong Dollar)", value: "HKD" },
  { name: "HUF (Hungarian Forint)", value: "HUF" },
  { name: "IDR (Indonesian Rupiah)", value: "IDR" },
  { name: "ILS (Israeli New Sheqel)", value: "ILS" },
  { name: "INR (Indian Rupee)", value: "INR" },
  { name: "JPY (Japanese Yen)", value: "JPY" },
  { name: "KES (Kenyan Shilling)", value: "KES" },
  { name: "KRW (South Korean Won)", value: "KRW" },
  { name: "LKR (Sri Lankan Rupee)", value: "LKR" },
  { name: "MAD (Moroccan Dirham)", value: "MAD" },
  { name: "MXN (Mexican Peso)", value: "MXN" },
  { name: "MYR (Malaysian Ringgit)", value: "MYR" },
  { name: "MZN (Mozambican Metical)", value: "MZN" },
  { name: "NAD (Namibian Dollar)", value: "NAD" },
  { name: "NOK (Norwegian Krone)", value: "NOK" },
  { name: "NZD (New Zealand Dollar)", value: "NZD" },
  { name: "PEN (Peruvian Sol)", value: "PEN" },
  { name: "PHP (Philippine Peso)", value: "PHP" },
  { name: "PLN (Polish Złoty)", value: "PLN" },
  { name: "RON (Romanian Leu)", value: "RON" },
  { name: "SEK (Swedish Krona)", value: "SEK" },
  { name: "SGD (Singapore Dollar)", value: "SGD" },
  { name: "THB (Thai Baht)", value: "THB" },
  { name: "TRY (Turkish Lira)", value: "TRY" },
  { name: "UAH (Ukrainian Hryvnia)", value: "UAH" },
  { name: "UYU (Uruguayan Peso)", value: "UYU" },
  { name: "XOF (West African Cfa Franc)", value: "XOF" },
  { name: "ZAR (South African Rand)", value: "ZAR" },
  { name: "ZMW (Zambian Kwacha)", value: "ZMW" },
] as const;

export type Currency = (typeof CURRENCIES)[number]["value"];
// eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- required for Zod, and can't be expressed by TS well
export const currencyCodes = CURRENCIES.map(({ value }) => value) as [Currency, ...Currency[]];

export const currencyByCountryCode = new Map<string, Currency>([
  ["AX", "EUR"],
  ["AS", "USD"],
  ["AD", "EUR"],
  ["AQ", "USD"],
  ["AR", "ARS"],
  ["AU", "AUD"],
  ["AT", "EUR"],
  ["BE", "EUR"],
  ["BJ", "XOF"],
  ["BQ", "USD"],
  ["BW", "BWP"],
  ["BV", "NOK"],
  ["IO", "USD"],
  ["BG", "BGN"],
  ["BF", "XOF"],
  ["CA", "CAD"],
  ["CL", "CLP"],
  ["CX", "AUD"],
  ["CC", "AUD"],
  ["CK", "NZD"],
  ["CR", "CRC"],
  ["CI", "XOF"],
  ["HR", "EUR"],
  ["CY", "EUR"],
  ["CZ", "CZK"],
  ["DK", "DKK"],
  ["EC", "USD"],
  ["EG", "EGP"],
  ["SV", "USD"],
  ["EE", "EUR"],
  ["FO", "DKK"],
  ["FI", "EUR"],
  ["FR", "EUR"],
  ["GF", "EUR"],
  ["TF", "EUR"],
  ["GE", "GEL"],
  ["DE", "EUR"],
  ["GH", "GHS"],
  ["GR", "EUR"],
  ["GL", "DKK"],
  ["GP", "EUR"],
  ["GU", "USD"],
  ["GG", "GBP"],
  ["GW", "XOF"],
  ["HM", "AUD"],
  ["VA", "EUR"],
  ["HK", "HKD"],
  ["HU", "HUF"],
  ["IN", "INR"],
  ["ID", "IDR"],
  ["IE", "EUR"],
  ["IM", "GBP"],
  ["IL", "ILS"],
  ["IT", "EUR"],
  ["JP", "JPY"],
  ["JE", "GBP"],
  ["KE", "KES"],
  ["KI", "AUD"],
  ["KR", "KRW"],
  ["LV", "EUR"],
  ["LI", "CHF"],
  ["LT", "EUR"],
  ["LU", "EUR"],
  ["MY", "MYR"],
  ["ML", "XOF"],
  ["MT", "EUR"],
  ["MH", "USD"],
  ["MQ", "EUR"],
  ["YT", "EUR"],
  ["MX", "MXN"],
  ["FM", "USD"],
  ["MC", "EUR"],
  ["ME", "EUR"],
  ["MA", "MAD"],
  ["MZ", "MZN"],
  ["NA", "NAD"],
  ["NR", "AUD"],
  ["NL", "EUR"],
  ["NZ", "NZD"],
  ["NE", "XOF"],
  ["NU", "NZD"],
  ["NF", "AUD"],
  ["MP", "USD"],
  ["NO", "NOK"],
  ["PW", "USD"],
  ["PS", "ILS"],
  ["PE", "PEN"],
  ["PH", "PHP"],
  ["PN", "NZD"],
  ["PL", "PLN"],
  ["PT", "EUR"],
  ["PR", "USD"],
  ["RE", "EUR"],
  ["RO", "RON"],
  ["BL", "EUR"],
  ["MF", "EUR"],
  ["PM", "EUR"],
  ["SM", "EUR"],
  ["SN", "XOF"],
  ["SG", "SGD"],
  ["SK", "EUR"],
  ["SI", "EUR"],
  ["ZA", "ZAR"],
  ["GS", "GBP"],
  ["ES", "EUR"],
  ["LK", "LKR"],
  ["SJ", "NOK"],
  ["SE", "SEK"],
  ["CH", "CHF"],
  ["TH", "THB"],
  ["TL", "IDR"],
  ["TG", "XOF"],
  ["TK", "NZD"],
  ["TR", "TRY"],
  ["TC", "USD"],
  ["TV", "AUD"],
  ["UA", "UAH"],
  ["AE", "AED"],
  ["GB", "GBP"],
  ["UM", "USD"],
  ["US", "USD"],
  ["UY", "UYU"],
  ["VG", "USD"],
  ["VI", "USD"],
  ["EH", "MAD"],
  ["ZM", "ZMW"],
  ["ZW", "USD"],
]);

export const MAX_WORKING_HOURS_PER_WEEK = 35;
export const WORKING_WEEKS_PER_YEAR = 44;
export const WEEKS_PER_YEAR = 52;
export const DAY_MS = 86400_000;

export const GOOGLE_AUTH_LIB_URL = "https://accounts.google.com/gsi/client";

export const countries = new Map<string, string>(
  Object.entries(c).map(([countryCode, info]) => [countryCode, info.countryName]),
);
export const supportedCountries = new Map<string, string>(
  Object.entries(c)
    .filter(([_, info]) => info.supportsWisePayout)
    .map(([countryCode, info]) => [countryCode, info.countryName]),
);
export const sanctionedCountries = new Map<string, string>(
  Object.entries(c)
    .filter(([_, info]) => info.sanctioned)
    .map(([countryCode, info]) => [countryCode, info.countryName]),
);
export { c as countryInfos };
